/* tslint:disable */
/* eslint-disable */
/**
 * ExerciseDB Documentation
 * This documentation provides detailed information about the ExerciseDB API available on RapidAPI. It includes various endpoints for accessing exercise data, such as images, equipment lists, and target muscle details, along with examples of required parameters and expected responses.
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

